### ISSUE TITLE
is there a way to add the set.yaml file manually?

### ISSUE THREAD

**Issue by otherperson684** [phillychi3/nhentai-favorites#12]
When I opened the nfavorites.py file, all it did was open and then close without doing anything. I don't know what error it showed since it went away so fast and that's also why I can't provide any screenshots. Please help

**Comment by phillychi3** [comment]
https://github.com/phillychi3/nhentai-favorites/issues/8#issuecomment-2331306173

**Comment by phillychi3** [comment]
If python closed so fast
You can try `python nfavorites.py` in cmd or other shell

**Comment by otherperson684** [comment]
Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: E:\spicy stuff\nhentai-favorites-main\nhentai-favorites-main\nfavorites.py
Traceback (most recent call last):
  File "E:\spicy stuff\nhentai-favorites-main\nhentai-favorites-main\nfavorites.py", line 1, in <module>
    from gettags import get_tags
  File "E:\spicy stuff\nhentai-favorites-main\nhentai-favorites-main\gettags.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

this was the error message I got

**Comment by phillychi3** [comment]
pip install -r ".\requirements.txt"
