### ISSUE TITLE
not downloading 

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [phillychi3/nhentai-favorites#4]
![image](https://github.com/phillychi3/nhentai-favorites/assets/73518754/cb84d3d0-00a8-47fb-8ce0-88484f2bf78c)

**Comment by phillychi3** [comment]
有錯誤訊息嗎？

**Comment by phillychi3** [comment]
用 ' 把資料包起來

**Comment by phillychi3** [comment]
cookid: 'example...'
useragent: 'same example'

**Comment by subsubsubsubsubsub** [comment]
![image](https://github.com/phillychi3/nhentai-favorites/assets/73518754/e2a178cc-8953-48d0-b657-96118bbdc88e)

not downloading

**Comment by phillychi3** [comment]
fix at #7
