### ISSUE TITLE
This happens

### ISSUE THREAD

**Issue by ignaciotortorelli** [phillychi3/nhentai-favorites#5]
C:\Users\Ignacio\Desktop\nhentai-favorites-main>python nfavorites.py
            _           _        _         ___  _
 _ __   ___| |__  _ __ | |_ __ _(_)       / __\/_\/\   /\
| '_ \ / _ \ '_ \| '_ \| __/ _` | |_____ / _\ //_\ \ / /
| | | |  __/ | | | | | | || (_| | |_____/ /  /  _  \ V /
|_| |_|\___|_| |_|_| |_|\__\__,_|_|     \/   \_/ \_/\_/

No offline data found, please wait a moment...
Traceback (most recent call last):
  File "nfavorites.py", line 94, in <module>
    get_tags()
  File "C:\Users\Ignacio\Desktop\nhentai-favorites-main\gettags.py", line 29, in get_tags
    useragent = yaml.load(f, Loader=yaml.CLoader)["useragent"]
TypeError: 'NoneType' object is not subscriptable

Please ask me for anything that might be relevant

**Comment by phillychi3** [comment]
hello
Had you edit or create set.yaml yet?

**Comment by ignaciotortorelli** [comment]
that was quick
![image](https://github.com/phillychi3/nhentai-favorites/assets/43938165/93451bd6-c5af-473e-ae5a-ec2d7579a5f1)
yes i have

**Comment by phillychi3** [comment]
@ignaciotortorelli fix now
Thanks for the report.

**Comment by ignaciotortorelli** [comment]
![image](https://github.com/phillychi3/nhentai-favorites/assets/43938165/d04dee56-3f49-48b3-840e-0ca1ddb0a4e1)
now this happens 😆
thank you for helping tho

**Comment by phillychi3** [comment]
try https://github.com/phillychi3/nhentai-favorites/blob/main/example_tag.json
rename example_tag.json -> tag.json
and run nfavorites.py again
or get cookie and useragent again

**Comment by ignaciotortorelli** [comment]
![image](https://github.com/phillychi3/nhentai-favorites/assets/43938165/08b9b32b-0a32-4824-8533-8fc9466403dd)
now i get this, also an output file is generated but is empty

**Comment by phillychi3** [comment]
no block by cloudflare error message
maby nologin in nhentai?

if no login ,it will output null csv in old vision

**Comment by ignaciotortorelli** [comment]
?
if you mean whether i am logged into nhentai, i am
i wouldn't be able to see my favorites if i wasn't

**Comment by phillychi3** [comment]
You can add 
```python
print(book)
```
in line 109
![image](https://github.com/phillychi3/nhentai-favorites/assets/55632143/3e0b0956-e86b-4a9e-900e-9f2b80a5504e)
to check what it's crawling

If nothing out
It means that's some error that I don't know about

Correct Output:
![image](https://github.com/phillychi3/nhentai-favorites/assets/55632143/4fe3ce40-71f4-40c6-b156-670404ffe119)

**Comment by ignaciotortorelli** [comment]
![image](https://github.com/phillychi3/nhentai-favorites/assets/43938165/bcf868f0-9650-4187-a383-60f7b14228e4)
nothing on either console nor the output.csv

**Comment by ignaciotortorelli** [comment]
anyway im going to sleep now
it was really nice of you to try <3 <3 <3 <3

**Comment by phillychi3** [comment]
sorry :(
I don't know what's wrong with it

The last resort was to see what its requests were crawling to.

![image](https://github.com/phillychi3/nhentai-favorites/assets/55632143/19162b15-101b-4064-91d4-868a05858e55)

good night.
