### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by trymap** [phillychi3/nhentai-favorites#7]
Thanks for the tool but the tool out put a csv with id,name,tags but with no data

![4](https://github.com/phillychi3/nhentai-favorites/assets/53605551/cc6a1671-f981-4c4c-9d1a-38b2e04a9696)
![1](https://github.com/phillychi3/nhentai-favorites/assets/53605551/f25736a2-4e2d-4663-8826-e91c9c3908c5)
![2](https://github.com/phillychi3/nhentai-favorites/assets/53605551/9e4a14b3-4f3a-4307-b0da-1c7343b7ac9c)
![3](https://github.com/phillychi3/nhentai-favorites/assets/53605551/a1f6f398-9754-4e44-abf0-c00fe9672592)

**Comment by trymap** [comment]
Is this UTF-8 problem?

![image](https://github.com/phillychi3/nhentai-favorites/assets/53605551/6209291c-a59e-4c2f-ad24-52660ffa8b1a)

**Comment by phillychi3** [comment]
試試看更新後的

**Comment by trymap** [comment]
回傳的值還是亂碼，而且不知道爲什麽結果會每一次都不一樣

![image](https://github.com/phillychi3/nhentai-favorites/assets/53605551/77a7a6ed-0079-4aa2-abb4-f72639612807)
![image](https://github.com/phillychi3/nhentai-favorites/assets/53605551/0ef2e7ab-5b01-4785-988f-b7fb7dc668d0)
![image](https://github.com/phillychi3/nhentai-favorites/assets/53605551/405f116a-ebea-466a-8004-23e3f29ed042)

**Comment by phillychi3** [comment]
試試看在Accept-Encoding裡面把br給移除
或者下載我剛更新的試試

**Comment by trymap** [comment]
成功了，非常感謝
