### ISSUE TITLE
page limit?

### ISSUE THREAD

**Issue by saplingdoko** [phillychi3/nhentai-favorites#9]
I tried downloading twice but the first time it got to 30 pages second time got to 20 pages but there are more pages to download

**Comment by phillychi3** [comment]
page xxx done is download tag
if you got problem
you can rename example_tag.json to tag.json

you need to check output.csv length is favorites+1
<img width="257" alt="截圖 2024-09-06 凌晨1 17 06" src="https://github.com/user-attachments/assets/db493f8d-451a-4299-84f2-da8553087705">
<img width="181" alt="截圖 2024-09-06 凌晨1 17 47" src="https://github.com/user-attachments/assets/2808e958-3b29-4221-8731-f46e0af52168">

**Comment by saplingdoko** [comment]
the csv length was short both times as well, I retried and I think the issue was that the website had too much traffic and was going down while trying to scrape. I tried again with no changes and it worked fine.
